version: '3'

services:
  # MySQL
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yhackday
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_HOST: '%'
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ${SAVE_PATH}:/var/lib/mysql
    - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
    - 3306:3306

  backend:
    build: .
    container_name: backend
    environment:
      SPRING_PROFILE: prd
      SPRING_CONFIG_LOCATION: classpath:application-prd.properties
    ports:
      - 8080:8080
